### ISSUE TITLE
evaluation

### ISSUE THREAD

**Issue by shapiro85** [fsmosca/PGN-Standard#2]
Hi Ferdy,
I hope you are doing very well and healthy in this crazy Covid 19 time's 
I would like to sort a big commented with evaluations Draw pgn database to white advantage ,black advantage.and none.
Could you please share an utility to do this task, if there is none would you kindly consider making one
best regards
Sam

**Comment by fsmosca** [comment]
I am doing ok. I hope you are doing fine as well.

I don't exactly understand your request. It is better to post in [talkchess](http://talkchess.com/forum3/index.php), detailing what you want.
